---
name: Lint

on: [push, pull_request]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
